[tool.poetry]
name = "maser.data"
version = "0.1.0"
description = ""
authors = ["Baptiste Cecconi <baptiste.cecconi@obspm.fr>"]
license = "CeCILL"

[tool.poetry.dependencies]
python = "^3.9"
spacepy = "^0.2.3"
astropy = "^5.0.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
